### ISSUE TITLE
feature request: make programs installable directly from GitHub

### ISSUE THREAD

**Issue by uvulpos** [Debian/apt#116]
Hi,
i've wanted to host my own debian apt repo for quite some time now, but i haven't found a good tutorial nor am i keen on the administration. So I had the idea to use GitHub in combination with apt https to offer fast and secure packages for installation (activatable for third party providers like me). I thought a bit in the direction of a composer. What do you think about the idea?

**Comment by DonKult** [comment]
https is adding a security layer for the transfer protocol http (hence the name). For securely acquiring packages (or updates or whatever your platform calls them) you need considerably more & ideally independent of the transport. Look under the hood of Microsoft Windows, Apple MacOS or the update mechanisms of big software on these platforms like Firefox or Chrome. apt (and similar on Linux platforms) "just" provides the same mechanisms but for everything in one place, so that individual software packages do not need to invent their own model all by themselves.

Removing what you consider complicated with keys and signing and all that means that we are susceptible to all sorts of problems e.g. programming language specific package managers who do this have currently and are unable to solve like type squatting. Having a secure way of transmitting a package is all fine, but you still have to make sure that the package is from who you think it is or you are potentially downloading malware over a secure transport.
