### ISSUE TITLE
Be transactional (enhancement)

### ISSUE THREAD

**Issue by raelgc** [Debian/apt#38]
Sometimes we'll have `apt` in a broken state. 

While we have several ways to solve the broken state, the easier and friendly way to behave should be rollback the action when a package produce a broken state and output a friendly message about the inability to run that action.

Something like this line: before upgrade a package, create a temporary copy of current related files, try to upgrade, and if this fails, restore the copy and present to the user a friendly message about the inability to upgrade.

**Comment by julian-klode** [comment]
Transactions are not possible.

**Comment by raelgc** [comment]
Well, the idea (improvement) is exactly make them possible.

Of course, I'm not an `apt` expert, I just create few of them eventually.

The general idea is this:

Let's suppose I asked to `apt` install package `x`. As dependency, apt will install `y` and `w` and a new version of `z` too.

Additionally, `x` will overwrite `/etc/foo` and it'll produce a diversion on `/usr/bar`.

So, just for the install session, we'll need to keep a copy of `/etc/foo`, `/usr/bar` and `z` installed files.

Let's suppose during the install, `w` has a broken `post.inst` script or a broken dependency. Instead of keep system in a break state, `apt` will revert everything for this session: restore `/etc/foo`, `/usr/bar` and `z` files to previous ones.

**Comment by julian-klode** [comment]
dpkg packages with maintainer scripts are inherently non-transactional by nature with maintainer scripts being able to do whatever they want. If you want transactional behavior, use snapshots in btrfs or lvm; or build something with ostree.

Now, for single packages, dpkg does atomic file renames and I think provides rollback for failed installations, but we cannot assume that anybody is testing that, so it likely would not work - and the system is often broken anyway regardless if the failed package is broken or not because some package depends on it.

Lastly, this is dpkg territory, not apt.

**Comment by raelgc** [comment]
@julian-klode: thank you for your time and patience to explain.
