### ISSUE TITLE
apt-key list --delete-expired-keys

### ISSUE THREAD

**Issue by reddyalready** [Debian/apt#53]
It would be great for `apt-key list --delete-expired-keys` to (obviously 😄 ) delete expired keys. Just putting this here in case anyone has pointers, but otherwise I'd like to try and add this feature in the next couple of weeks.

**Comment by DonKult** [comment]
Hi reddyalready! (Interesting nick :) )

"list" sounds very much like a read-only action, so I would like to avoid confusion by making it do things. From an UI point of view an option for the remove command would be better. Also, you probably meant apt-key, not apt-get.

Anyhow, what is the usecase for this? Expired keys are pretty harmless given that they can't be used, as a user I would be more worried about keys I don't need anymore but still have lying around (which potentially never expire or do so only after a looooong time).

Regarding pointers: apt-key is a shellscript wrapping around gnupg (1.x and 2.x), so if you can express your wish on the commandline with gnupg you can massage it into apt-key-code as well.

**Comment by reddyalready** [comment]
Thanks @DonKult (I thought long and hard about it :) )

The use-case I had was when attempting to script our `apt-get update/install openvpn`, the signing key is fairly short-lived (see [OpenVPN Repo Instructions](https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos#Notesonexpiredkeys) 

Unless there's an easier way to do it, I had thought of writing an `awk/grep + apt-key delete`, but then thought perhaps this could be useful to others as well.

(And yes, I meant `apt-key` and not `apt-get`, fixed in the issue!)

**Comment by DonKult** [comment]
May I suggest redoing this setup for everyone's benefit?

I would introduce an openvpn-archive-keyring package (similar to debian-archive-keyring and co) which ships your currently supported key(s) in an /etc/apt/trusted.gpg.d/ file. This way users have to get a file only once in a "complicated-secure" way instead of repeatedly.

Depending on your security preferences you can either prompt users to install this package once (after downloading it via https) with either dpkg -i (or in apt >= 1.1 with as "normal" with apt install /path/to/pkg.deb) OR let them drop a key in /etc/apt/trusted.gpg.d/ manually, prompt them to install install the keyring package after that & remove the manually created file again (now that the package is installed the keys are available in other keyring files, too).

Apart from this user-improvement, the reason I would try to avoid using apt-key is that it isn't guaranteed to work as apt isn't depending on gnupg anymore as it doesn't need it for its normal operations anymore so it seems irrational to force it to be installed by default everywhere, so we don't. So especially on new installs and/or recent releases apt-key will just refuse to function until the user installs additional packages instead of doing what the instructions suggest which makes them even less user-friendly.

**Comment by reddyalready** [comment]
This makes a lot more sense, I'll ask the OpenVPN folks what they think of this. Happy to close the issue.

Cheers,
Bharat

**Comment by rootkea** [comment]
So, how to delete all the expired keys?
Can we have `apt-key --delete-expired-keys`?
