### ISSUE TITLE
Redundant options : --upgradable and --upgradeable

### ISSUE THREAD

**Issue by Gu1nness** [Debian/apt#60]
From [what I see](https://github.com/Debian/apt/blob/ca2fcc639c7363a04998f650b96573d806b32dd2/apt-private/private-cmndline.cc#L330) , the two options ```--upgradable``` and ```--upgradeable``` are nearly the same, except that ```--upgradable ``` has a short version ( ``` -u ```)

Is there any reason to keep both options ?
This can help in maintaining a consistent documentation in the man pages, without forgetting some options ( see [here](https://github.com/Debian/apt/blob/master/doc/apt.8.xml#L131)

I can remove the options and create a PR if you want.

**Comment by julian-klode** [comment]
It's a feature :) I added a few alternative spellings like that because they are often mistyped and it's really annoying to be so strict about them.  Same for `--auto-remove` and `--autoremove`. We can add these spellings to documentation, but I'm not sure it's really needed - I feel like there should be one official one.
